### ISSUE TITLE
SVGparser not importing

### ISSUE THREAD

**Issue by Trimonix** [mpbagot/IPT_Vector_Project#1]
![capture](https://user-images.githubusercontent.com/26248345/27993901-879daa6a-64f5-11e7-8198-a23239f99058.JPG)

**Comment by mpbagot** [comment]
Issue was with the naming used for the Parser file. 'parser' is a module in the Python Standard Library and a naming conflict occurred when the server was run on Windows systems.

Issue has been fixed by renaming the parser module to svg_parser.
